# **Demonstration**

## **1. Data Acquisition**

**Importing required libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Loading an example dataset**

In [2]:
# get the dataset from sklearn
from sklearn.datasets import load_breast_cancer

In [3]:
cancer = load_breast_cancer()

In [4]:
type(cancer)

sklearn.utils._bunch.Bunch

In [5]:
cancer
#the data set is presented in a dictionary form

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [6]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
len(cancer["data"][0])

30

We can grab information and arrays out of this dictionary to set up our data frame and understanding of the features:

In [8]:
print(cancer["DESCR"])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [9]:
sum(cancer["target"])

357

In [10]:
cancer["target"]==0
#1- benign
#0- malignant

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False, False, False, False,  True,
        True, False,  True,  True, False, False, False, False,  True,
       False,  True,  True, False, False, False, False,  True, False,
        True,  True, False,  True, False,  True,  True, False, False,
       False,  True,  True, False,  True,  True,  True, False, False,
       False,  True, False, False,  True,  True, False, False, False,
        True,  True, False, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
        True,  True,  True, False,  True,  True, False, False, False,
        True,  True,

In [11]:
cancer["feature_names"]

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

## **2. Data Cleaning**

### **Setting Up DataFrames**

In [12]:
cancer["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [13]:
df_target = pd.DataFrame(cancer["target"], columns=["Cancer"])

In [14]:
df_target

Cancer
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

In [15]:
df_features= pd.DataFrame(data=cancer["data"], columns=cancer["feature_names"])
df_features

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

### **Data Cleaning**

In [16]:
df_features.isnull().any()

mean radius                False
mean texture               False
mean perimeter             False
mean area                  False
mean smoothness            False
mean compactness           False
mean concavity             False
mean concave points        False
mean symmetry              False
mean fractal dimension     False
radius error               False
texture error              False
perimeter error            False
area error                 False
smoothness error           False
compactness error          False
concavity error            False
concave points error       False
symmetry error             False
fractal dimension error    False
worst radius               False
worst texture              False
worst perimeter            False
worst area                 False
worst smoothness           False
worst compactness          False
worst concavity            False
worst concave points       False
worst symmetry             False
worst fractal dimension    False
dtype: boo

## **3. Model Training & Building**

### **X and y arrays**

In [17]:
X = df_features
y = df_target

### **Train Test Split**

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=101)

In [20]:
X_train

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
178       13.010         22.22           82.01      526.4          0.06251   
421       14.690         13.98           98.22      656.1          0.10310   
57        14.710         21.59           95.55      656.9          0.11370   
514       15.050         19.07           97.26      701.9          0.09215   
548        9.683         19.34           61.05      285.7          0.08491   
..           ...           ...             ...        ...              ...   
552       12.770         29.43           81.35      507.9          0.08276   
393       21.610         22.28          144.40     1407.0          0.11670   
75        16.070         19.65          104.10      817.7          0.09168   
337       18.770         21.43          122.90     1092.0          0.09116   
523       13.710         18.68           88.73      571.0          0.09916   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
178           0.01938        0.001595             0.001852         0.1395   
421           0.18360        0.145000             0.063000         0.2086   
57            0.13650        0.129300             0.081230         0.2027   
514           0.08597        0.074860             0.043350         0.1561   
548           0.05030        0.023370             0.009615         0.1580   
..                ...             ...                  ...            ...   
552           0.04234        0.019970             0.014990         0.1539   
393           0.20870        0.281000             0.156200         0.2162   
75            0.08424        0.097690             0.066380         0.1798   
337           0.14020        0.106000             0.060900         0.1953   
523           0.10700        0.053850             0.037830         0.1714   

     mean fractal dimension  ...  worst radius  worst texture  \
178                 0.05234  ...         14.00          29.02   
421                 0.07406  ...         16.46          18.34   
57                  0.06758  ...         17.87          30.70   
514                 0.05915  ...         17.58          28.06   
548                 0.06235  ...         10.93          25.59   
..                      ...  ...           ...            ...   
552                 0.05637  ...         13.87          36.00   
393                 0.06606  ...         26.23          28.74   
75                  0.05391  ...         19.77          24.56   
337                 0.06083  ...         24.54          34.37   
523                 0.06843  ...         15.11          25.63   

     worst perimeter  worst area  worst smoothness  worst compactness  \
178            88.18       608.8           0.08125            0.03432   
421           114.10       809.2           0.13120            0.36350   
57            115.70       985.5           0.13680            0.42900   
514           113.80       967.0           0.12460            0.21010   
548            69.10       364.2           0.11990            0.09546   
..               ...         ...               ...                ...   
552            88.10       594.7           0.12340            0.10640   
393           172.00      2081.0           0.15020            0.57170   
75            128.80      1223.0           0.15000            0.20450   
337           161.10      1873.0           0.14980            0.48270   
523            99.43       701.9           0.14250            0.25660   

     worst concavity  worst concave points  worst symmetry  \
178         0.007977              0.009259          0.2295   
421         0.321900              0.110800          0.2827   
57          0.358700              0.183400          0.3698   
514         0.286600              0.112000          0.2282   
548         0.093500              0.038460          0.2552   
..               ...                   ...             ...   
552         0.086530              0.064980         

In [21]:
y_train

Cancer
178       1
421       1
57        0
514       0
548       1
..      ...
552       1
393       0
75        0
337       0
523       1

[398 rows x 1 columns]

### **Creating and Training the Model**

**i) Importing a model**

In [41]:
# Select a model
from sklearn.svm import SVC


**ii) Instantiation**

In [23]:
# Instantiate
model = SVC() # default: kernel = 'rbf'

In [24]:
model

SVC()

**iii) Model fitting**

In [25]:
model.fit(X_train, y_train)

C:\Users\afkjh\DataspellProjects\untitled\venv\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

## **4. Model Prediction & Evaluation**

### **Prediction**

In [26]:
pred= model.predict(X_test)
pred

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1])

In [27]:
np.array(y_test["Cancer"].tolist())

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0])

### **Evaluation**

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [29]:
print(accuracy_score(y_test,pred))

0.9239766081871345


In [30]:
print(confusion_matrix(y_test, pred))

[[ 56  10]
 [  3 102]]


In [31]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.95      0.85      0.90        66
           1       0.91      0.97      0.94       105

    accuracy                           0.92       171
   macro avg       0.93      0.91      0.92       171
weighted avg       0.93      0.92      0.92       171


## **Implementing Kernel SVM**

### **1) Linear Kernel**

In [32]:
model2=SVC(kernel="linear") # the linear kernel works fine if your dataset if linearly separable

In [33]:
model2

SVC(kernel='linear')

In [34]:
model2.fit(X_train, y_train)

C:\Users\afkjh\DataspellProjects\untitled\venv\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [35]:
pred2= model2.predict(X_test)
pred2

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1])

In [36]:
print(accuracy_score(y_test, pred2))

0.9473684210526315


### **2. Polynomial Kernel**

In [37]:
model3=SVC(kernel="poly")
model3.fit(X_train, y_train)
pred3= model3.predict(X_test)
print(accuracy_score(y_test, pred3))

0.9064327485380117


C:\Users\afkjh\DataspellProjects\untitled\venv\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### **3. Gaussian Kernel**

In [38]:
model4=SVC(kernel="rbf")
model4.fit(X_train, y_train)
pred4= model4.predict(X_test)
print(accuracy_score(y_test, pred4))

0.9239766081871345


C:\Users\afkjh\DataspellProjects\untitled\venv\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### **4. Sigmoid Kernel**

In [39]:
model5=SVC(kernel="sigmoid")
model5.fit(X_train, y_train)
pred5= model5.predict(X_test)
print(accuracy_score(y_test, pred5))

0.4152046783625731


C:\Users\afkjh\DataspellProjects\untitled\venv\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [40]:
# sigmoid kernel: the worst -> returns two values, 0 and 1 -> for binary classification problems